name: Paint Ease CI 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
  pages: 'write'
  actions: 'write'
  checks: 'write'
  deployments: 'write'

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  #Setup Job install dependencies and lint validate
  setup:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Setup/ Checkout
        uses: actions/checkout@v4
        
      - name: Setup/ Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8
          
      - name: Setup/ Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup/ Install dependencies
        run: pnpm install

      - name: Lint/ Validate current commit (last commit) with commitlint
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge pull request') && !contains(github.event.head_commit.message, 'Merge branch') }}
        run: npx commitlint --last --verbose

      - name: Lint/ Run ESLint
        run: pnpm lint
        
      - name: Build the app
        if: ${{ github.ref == 'refs/heads/main' }}
        run: pnpm run build
        
      - name: Setup pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v5.0.0
        
      - name: Upload GitHub Pages artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist
        
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
