name: Paint Ease CI 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup/ Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup/ Install dependencies
        run: npm ci

      - name: Lint/ Validate current commit (last commit) with commitlint
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge pull request') && !contains(github.event.head_commit.message, 'Merge branch') }}
        run: npx commitlint --last --verbose

      - name: Lint/ Validate PR commits with commitlint
        if: ${{ github.event_name == 'pull_request' }}
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
     
      - uses: actions/checkout@v3
      - name: Lint/ Run ESLint
        run: npm run lint

      - name: Deploy/ Build the app
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        run: npm run build

      - name: Deploy/ Setup Pages
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/configure-pages@v3

      - name: Deploy/ Upload artifact
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'

      - name: Deploy/ Deploy to GitHub Pages
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/deploy-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: eslint
    runs-on: ubuntu-latest
    if: ${{ success() && github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'
      actions: 'write'
      checks: 'write'
      deployments: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Build the app
        run: npm run build 

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        environment:
          name: github-pages
        permissions:
          contents: 'read'
          id-token: 'write'
          pages: 'write'
          actions: 'write'
          checks: 'write'
          deployments: 'write'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
